import "../styles/globals.css"
import Header from "./Header"

export const metadata = {
  title: 'Chris App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
